fix(ci): build API document
Since the API build job does not fetch build artifacts,
it fails due to missing type declarations.
Move build-docs after the validate job to ensure that
only verified documentation is published and to fix the type errors.

```
src/index.ts:54:33 - error TS2307: Cannot find module '../dist/thorvg' or its corresponding type declarations.

54 import ThorVGModuleFactory from '../dist/thorvg';
```